name: Release
on:
  push:
    branches:
      - main
concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions:
  contents: write
  packages: write
  pull-requests: write
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          registry-url: 'https://npm.pkg.github.com'
          scope: 'siplyvoice'
      - name: Install dependencies
        run: pnpm install
      - name: Create Release Pull Request or Publish packages
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create git tag for golang package
        if: steps.changesets.outputs.published == 'true'
        uses: rickstaa/action-create-tag@v1
        id: tag_create
        with:
          tag: ${{format('v{0}', fromJson(steps.changesets.outputs.publishedPackages)[0].version)}}
          tag_exists_error: false
          message: "@siplyvoice/livekit-protocol@${{fromJson(steps.changesets.outputs.publishedPackages)[0].version}}"