name: Release
on:
  push:
    branches:
      - main
permissions:
  contents: write
  packages: write
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          registry-url: 'https://npm.pkg.github.com'
          scope: 'siplyvoice'
      - name: Install dependencies
        run: pnpm install
      - name: Build and publish
        run: |
          pnpm build
          pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create git tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{format('v{0}', steps.VERSION.outputs.version)}}
          message: "Release v${{steps.VERSION.outputs.version}}"